#include <stdio.h>

#define BYTE_WHITESPACE         (1 << 0)
#define BYTE_LINE_TERMINATOR    (1 << 1)
#define BYTE_QUOTE              (1 << 2)
#define BYTE_ASCII_STRING       (1 << 3)
#define BYTE_COMMENT            (1 << 4)
#define BYTE_0_9                (1 << 5)
#define BYTE_1_9                (1 << 6)
#define BYTE_HEX_DIGIT          (1 << 7)
#define BYTE_EXPONENT           (1 << 8)
#define BYTE_EXPONENT_SIGN      (1 << 9)
#define BYTE_ESCAPE             (1 << 10)
#define BYTE_LEADER_2           (1 << 11)
#define BYTE_LEADER_3           (1 << 12)
#define BYTE_LEADER_4           (1 << 13)
#define BYTE_CONTINUATION       (1 << 14)
#define BYTE_E0_NEXT            (1 << 15)
#define BYTE_ED_NEXT            (1 << 16)
#define BYTE_F0_NEXT            (1 << 17)
#define BYTE_F4_NEXT            (1 << 18)

int main()
{
        printf("// Generated by make_byte_map\n\n");
        printf("static const unsigned byte_map[] = {");
        for(int i = 0 ; i < 256 ; i++) {
                unsigned mask;
                if(i == '\t')
                        mask = BYTE_WHITESPACE;
                else if(i == '\n' || i == '\r')
                        mask = BYTE_WHITESPACE | BYTE_LINE_TERMINATOR;
                else if(i < ' ')
                        mask = 0;
                else if(i == ' ')
                        mask = BYTE_ASCII_STRING | BYTE_WHITESPACE;
                else if(i < '"')
                        mask = BYTE_ASCII_STRING;
                else if(i == '"')
                        mask = BYTE_QUOTE;
                else if(i < '+')
                        mask = BYTE_ASCII_STRING;
                else if(i == '+')
                        mask = BYTE_ASCII_STRING;
                else if(i == ',')
                        mask = BYTE_ASCII_STRING;
                else if(i == '-')
                        mask = BYTE_ASCII_STRING;
                else if(i == '.')
                        mask = BYTE_ASCII_STRING;
                else if(i == '/')
                        mask = BYTE_ASCII_STRING | BYTE_COMMENT;
                else if(i == '0')
                        mask = BYTE_ASCII_STRING | BYTE_0_9 | BYTE_HEX_DIGIT;
                else if(i <= '9')
                        mask = BYTE_ASCII_STRING | BYTE_0_9 | BYTE_1_9| BYTE_HEX_DIGIT;
                else if(i == ':')
                        mask = BYTE_ASCII_STRING;
                else if(i < 'A')
                        mask = BYTE_ASCII_STRING;
                else if(i <= 'F')
                        mask = BYTE_ASCII_STRING | BYTE_HEX_DIGIT;
                else if(i < '[')
                        mask = BYTE_ASCII_STRING;
                else if(i == '[')
                        mask = BYTE_ASCII_STRING;
                else if(i == '\\')
                        mask = BYTE_ESCAPE;
                else if(i == ']')
                        mask = BYTE_ASCII_STRING;
                else if(i < 'a')
                        mask = BYTE_ASCII_STRING;
                else if(i < 'g')
                        mask = BYTE_ASCII_STRING | BYTE_HEX_DIGIT;
                else if(i < '{')
                        mask = BYTE_ASCII_STRING;
                else if(i == '{')
                        mask = BYTE_ASCII_STRING;
                else if(i == '|')
                        mask = BYTE_ASCII_STRING;
                else if(i == '}')
                        mask = BYTE_ASCII_STRING;
                else if(i < 0x80)
                        mask = BYTE_ASCII_STRING;
                else if(i <= 0xBF)
                        mask = BYTE_CONTINUATION;
                else if(i >= 0xC2 && i <= 0xDF)
                        mask = BYTE_LEADER_2;
                else if(i <= 0xEF)
                        mask = BYTE_LEADER_3;
                else if(i <= 0xF4)
                        mask = BYTE_LEADER_4;
                else
                        mask = 0;

                if(i == 0)
                        printf("\n        ");
                else if(0 == i % 8)
                        printf(",\n        ");
                else
                        printf(", ");

                printf("0x%X", mask);
        }
        printf("\n};");

        printf("\nstatic const unsigned byte_map_extra[] = {");
        for(int i = 0 ; i < 256 ; i++) {
                unsigned extra;

                // Extra for hex digits is their value
                if(i >= '0' && i <= '9')
                        extra = i - '0';
                else if(i >= 'A' && i <= 'F')
                        extra = 10 + i - 'A';
                else if(i >= 'a' && i <= 'f')
                        extra = 10 + i - 'a';

                // extra for UTF-8 leaders is their first continuation
                else if(i == 0xE0)
                        extra = BYTE_E0_NEXT;
                else if(i == 0xED)
                        extra = BYTE_ED_NEXT;
                else if(i == 0xF0)
                        extra = BYTE_F0_NEXT;
                else if(i == 0xF4)
                        extra = BYTE_F4_NEXT;
                else if(i >= 0xC2 && i < 0xF4)
                        extra = BYTE_CONTINUATION;
                else
                        extra = 0;

               if(i == 0)
                        printf("\n        ");
                else if(0 == i % 8)
                        printf(",\n        ");
                else
                        printf(", ");

                printf("0x%X", extra);
        }
        printf("\n};");

}


