#include <stdio.h>

#define BYTE_WHITESPACE         (1 << 0)
#define BYTE_QUOTE              (1 << 1)
#define BYTE_ASCII_STRING       (1 << 2)
#define BYTE_COMMENT            (1 << 3)
#define BYTE_0_9                (1 << 4)
#define BYTE_1_9                (1 << 5)
#define BYTE_HEX_DIGIT          (1 << 6)
#define BYTE_EXPONENT           (1 << 7)
#define BYTE_EXPONENT_SIGN      (1 << 8)
#define BYTE_ESCAPE             (1 << 9)
#define BYTE_LEADER_2           (1 << 10)
#define BYTE_LEADER_3           (1 << 11)
#define BYTE_E0                 (1 << 12)
#define BYTE_ED                 (1 << 13)
#define BYTE_LEADER_4           (1 << 14)
#define BYTE_F0                 (1 << 15)
#define BYTE_F4                 (1 << 16)
#define BYTE_CONTINUATION       (1 << 17)
#define BYTE_E0_NEXT            (1 << 18)
#define BYTE_ED_NEXT            (1 << 19)
#define BYTE_F0_NEXT            (1 << 20)
#define BYTE_F4_NEXT            (1 << 21)
#define BYTE_POINT              (1 << 22)
#define BYTE_OPEN_BRACE         (1 << 23)
#define BYTE_CLOSE_BRACE        (1 << 24)
#define BYTE_OPEN_BRACKET       (1 << 25)
#define BYTE_CLOSE_BRACKET      (1 << 26)
#define BYTE_COMMA              (1 << 27)
#define BYTE_COLON              (1 << 28)
#define BYTE_MINUS              (1 << 29)
#define BYTE_BACKSLASH          (1 << 30)
#define BYTE_0                  (1 << 31)

int main()
{
        printf("// Generated by make_byte_map\n\n");
        printf("static const unsigned byte_map[] = {");
        for(int i = 0 ; i < 256 ; i++) {
                unsigned mask;
                if(i == '\t' || i == '\n' || i == '\r')
                        mask = BYTE_WHITESPACE;
                else if(i < ' ')
                        mask = 0;
                else if(i == ' ')
                        mask = BYTE_ASCII_STRING | BYTE_WHITESPACE;
                else if(i < '"')
                        mask = BYTE_ASCII_STRING;
                else if(i == '"')
                        mask = BYTE_QUOTE | BYTE_ESCAPE;
                else if(i < '+')
                        mask = BYTE_ASCII_STRING;
                else if(i == '+')
                        mask = BYTE_ASCII_STRING | BYTE_EXPONENT_SIGN;
                else if(i == ',')
                        mask = BYTE_ASCII_STRING | BYTE_COMMA;
                else if(i == '-')
                        mask = BYTE_ASCII_STRING | BYTE_MINUS | BYTE_EXPONENT_SIGN;
                else if(i == '.')
                        mask = BYTE_ASCII_STRING | BYTE_POINT;
                else if(i == '/')
                        mask = BYTE_ASCII_STRING | BYTE_COMMENT | BYTE_ESCAPE;
                else if(i == '0')
                        mask = BYTE_ASCII_STRING | BYTE_0 | BYTE_0_9;
                else if(i <= '9')
                        mask = BYTE_ASCII_STRING | BYTE_0_9 | BYTE_1_9;
                else if(i == ':')
                        mask = BYTE_ASCII_STRING | BYTE_COLON;
                else if(i < 'A')
                        mask = BYTE_ASCII_STRING;
                else if(i <= 'F')
                        mask = BYTE_ASCII_STRING | BYTE_HEX_DIGIT;
                else if(i < '[')
                        mask = BYTE_ASCII_STRING;
                else if(i == '[')
                        mask = BYTE_ASCII_STRING | BYTE_OPEN_BRACKET;
                else if(i == '\\')
                        mask = BYTE_BACKSLASH | BYTE_ESCAPE;
                else if(i == ']')
                        mask = BYTE_ASCII_STRING | BYTE_CLOSE_BRACKET;
                else if(i < 'a')
                        mask = BYTE_ASCII_STRING;
                else if(i < 'g')
                        mask = BYTE_ASCII_STRING | BYTE_HEX_DIGIT;
                else if(i < '{')
                        mask = BYTE_ASCII_STRING;
                else if(i == '{')
                        mask = BYTE_ASCII_STRING | BYTE_OPEN_BRACE;
                else if(i == '|')
                        mask = BYTE_ASCII_STRING;
                else if(i == '}')
                        mask = BYTE_ASCII_STRING | BYTE_CLOSE_BRACE;
                else if(i < 0x80)
                        mask = BYTE_ASCII_STRING;
                else if(i <= 0x8F)
                        mask = BYTE_CONTINUATION | BYTE_ED_NEXT | BYTE_F4_NEXT;
                else if(i <= 0x9F)
                        mask = BYTE_CONTINUATION | BYTE_ED_NEXT | BYTE_F0_NEXT;
                else if(i <= 0xA0)
                        mask = BYTE_CONTINUATION | BYTE_F0_NEXT;
                else if(i <= 0xBF)
                        mask = BYTE_CONTINUATION | BYTE_E0_NEXT | BYTE_F0_NEXT;
                else if(i >= 0xC2 && i <= 0xDF)
                        mask = BYTE_LEADER_2;
                else if(i == 0xE0)
                        mask = BYTE_LEADER_3 | BYTE_E0;
                else if(i <= 0xEC)
                        mask = BYTE_LEADER_3;
                else if(i == 0xED)
                        mask = BYTE_LEADER_3 | BYTE_ED;
                else if(i <= 0xEF)
                        mask = BYTE_LEADER_3;
                else if(i == 0xF0)
                        mask = BYTE_LEADER_4 | BYTE_F0;
                else if(i < 0xF4)
                        mask = BYTE_LEADER_4;
                else if(i == 0xF4)
                        mask = BYTE_LEADER_4 | BYTE_F4;
                else
                        mask = 0;

                if(i == 0)
                        printf("\n        ");
                else if(0 == i % 8)
                        printf(",\n        ");
                else
                        printf(", ");

                printf("0x%X", mask);
        }
        printf("\n};");

        printf("\nstatic const unsigned byte_map_next[] = {");
        for(int i = 0 ; i < 256 ; i++) {
                unsigned next;


                if(i == 0xE0)
                        next = BYTE_E0_NEXT;
                else if(i == 0xED)
                        next = BYTE_ED_NEXT;
                else if(i == 0xF0)
                        next = BYTE_F0_NEXT;
                else if(i == 0xF4)
                        next = BYTE_F4_NEXT;
                else if(i >= 0xC2 && i < 0xF4)
                        next = BYTE_CONTINUATION;
                else
                        next = 0;

               if(i == 0)
                        printf("\n        ");
                else if(0 == i % 8)
                        printf(",\n        ");
                else
                        printf(", ");

                printf("0x%X", next);
        }
        printf("\n};");

}


